services:
  noteilus_client:
    image: noteilus_client:v1
    build: ./fe
    ports:
      - 80:80 # Nginx가 80 포트로 서빙함
    volumes:
      - ./fe:/app

  noteilus_server:
    image: noteilus_server:v1
    build:
      context: .
      dockerfile: be/dockerfile
    ports:
      - 8080:8080
    environment:
      # DB URI
      - MONGODB_URI_KEY=${MONGODB_URI_KEY}

      # OAuth (google)
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}

      # OAuth (kakao)
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}

      # Session
      - SESSION_SECRET=${SESSION_SECRET}

      # etc
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      

    depends_on:
      - noteilus_client
    develop:
      watch:
        - action: sync+restart
          path: ./be # 지켜볼 경로
          target: /app

        - action: rebuild
          path: package.json
