services:
  noteilus_client:
    image: noteilus_client:v1
    build: ./fe
    ports:
      - 80:80 # Nginx가 80 포트로 서빙함
    volumes:
      - ./fe:/app
    depends_on:
      - noteilus_server
    

  noteilus_server:
    image: noteilus_server:v1
    build:
      context: .
      dockerfile: be/dockerfile
    ports:
      - 8080:8080
    environment:
      # DB URI
      - MONGODB_URI_KEY=${MONGODB_URI_KEY}
      # OAuth (google)
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      # OAuth (kakao)
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      # Session
      - SESSION_SECRET=${SESSION_SECRET}
      # AWS S3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      # Mistral AI
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      # etc
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      

    develop:
      watch:
        - action: sync+restart
          path: ./be # 지켜볼 경로
          target: /app

        - action: rebuild
          path: package.json