# 백엔드 스테이지
FROM node:22-alpine
WORKDIR /app

# Poppler 유틸리티, GraphicsMagick, Ghostscript 설치 (pdf2pic이 필요로 함)
RUN apk add --no-cache poppler-utils graphicsmagick ghostscript

COPY be/package*.json .
RUN npm install

ENV NODE_ENV=production

COPY be/ .

EXPOSE 8080

USER node
CMD ["node", "server.js"]